sudo: false
dist: xenial
language: python
python: 3.7
matrix:
  fast_finish: true
services:
  - postgresql
install:
  - pip install -r requirements_test.txt
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - tox
after_success:
  - codecov
